/**
 * @enum ECommunityBadgeQuests
 */
module.exports = {
    'AddFriendToFriendsList': 113,
    'AddItemToWishlist': 108,
    'AddPhoneToAccount': 128,
    'AddTwoFactorToAccount': 134,
    'BuyOrSellOnMarket': 120,
    'CraftGameBadge': 124,
    'FeatureBadgeOnProfile': 127,
    'JoinGroup': 101,
    'PlayGame': 112,
    'PostCommentOnFriendsPage': 103,
    'PostCommentOnFriendsScreenshot': 109,
    'PostScreenshot': 105,
    'PostStatusToFriends': 117,
    'PostVideo': 106,
    'RateUpContentInActivityFeed': 118,
    'RateWorkshopItem': 114,
    'RecommendGame': 104,
    'SearchInDiscussions': 123,
    'SetProfileBackground': 126,
    'SetupCommunityAvatar': 110,
    'SetupCommunityRealName': 111,
    'SetupSteamGuard': 115,
    'SubscribeToWorkshopItem': 119,
    'Trade': 122,
    'UseDiscoveryQueue': 132,
    'UseEmoticonInChat': 125,
    'ViewBroadcast': 133,
    'ViewGuideInOverlay': 121,

    // Value-to-name mapping for convenience
    '101': 'JoinGroup',
    '103': 'PostCommentOnFriendsPage',
    '104': 'RecommendGame',
    '105': 'PostScreenshot',
    '106': 'PostVideo',
    '108': 'AddItemToWishlist',
    '109': 'PostCommentOnFriendsScreenshot',
    '110': 'SetupCommunityAvatar',
    '111': 'SetupCommunityRealName',
    '112': 'PlayGame',
    '113': 'AddFriendToFriendsList',
    '114': 'RateWorkshopItem',
    '115': 'SetupSteamGuard',
    '117': 'PostStatusToFriends',
    '118': 'RateUpContentInActivityFeed',
    '119': 'SubscribeToWorkshopItem',
    '120': 'BuyOrSellOnMarket',
    '121': 'ViewGuideInOverlay',
    '122': 'Trade',
    '123': 'SearchInDiscussions',
    '124': 'CraftGameBadge',
    '125': 'UseEmoticonInChat',
    '126': 'SetProfileBackground',
    '127': 'FeatureBadgeOnProfile',
    '128': 'AddPhoneToAccount',
    '132': 'UseDiscoveryQueue',
    '133': 'ViewBroadcast',
    '134': 'AddTwoFactorToAccount',
};
